ANDROID: arm64: fix ftrace due to bad cherry-picks from mainline v3.19
Three patches were cherry-picked incorrectly from mainline to android-3.18:

c852f32 arm64: Emulate CP15 Barrier instructions
bd35a4a arm64: Port SWP/SWPB emulation support from arm
9b79f52 arm64: Add support for hooks to handle undefined instructions

In all cases, the added hunks should have been above
"#endif /*__ASSEMBLY */" in arch/arm64/include/asm/insn.h.

The bad merge breaks ftrace compilation on arm64 (e.g. with the following
lines added to arch/arm64/configs/defconfig):
 CONFIG_FTRACE=y
 CONFIG_FUNCTION_TRACER=y

Here is the breakage:
  AS      arch/arm64/kernel/entry-ftrace.o
./arch/arm64/include/asm/insn.h: Assembler messages:
./arch/arm64/include/asm/insn.h:359: Error: unknown mnemonic `bool' -- `bool aarch32_insn_is_wide(u32 insn)'
./arch/arm64/include/asm/insn.h:365: Error: unknown mnemonic `u32' -- `u32 aarch32_insn_extract_reg_num(u32 insn,int offset)'
./arch/arm64/include/asm/insn.h:366: Error: unknown mnemonic `u32' -- `u32 aarch32_insn_mcr_extract_opc2(u32 insn)'
./arch/arm64/include/asm/insn.h:367: Error: unknown mnemonic `u32' -- `u32 aarch32_insn_mcr_extract_crm(u32 insn)'
scripts/Makefile.build:293: recipe for target 'arch/arm64/kernel/entry-ftrace.o' failed

Signed-off-by: Daniel Kurtz <djkurtz@google.com>
(cherry picked from commit 5ab8b1104af542d07c80930c58f558cbbca319af)
Signed-off-by: Stephen Barber <smbarber@chromium.org>

BUG=none
TEST=kernel compiles and boots

Change-Id: Ia196b9a7373ca121081d491d1ce9582d39b5d0ce
Reviewed-on: https://chromium-review.googlesource.com/281638
Reviewed-by: Dylan Reid <dgreid@chromium.org>
Tested-by: Stephen Barber <smbarber@chromium.org>
Commit-Queue: Stephen Barber <smbarber@chromium.org>