CHROMIUM: net: tcp: Only perform IPv6 functions is IPv6 is built-in
Build error with IPv6 built as module:

net/built-in.o: In function `tcp_is_local6':
net/ipv4/tcp.c:3156: undefined reference to `rt6_lookup'

Alternative would be to define IPV6 as boolean, but that causes trouble
elsewhere.

Fixes: c7c3ec4903d3 ("net: socket ioctl to reset connections matching local address")
BUG=chromium:583462
TEST=None (build)

Change-Id: I98ef6d237b79355004ffdc223bce2e23fe368437
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325394
Reviewed-by: Dylan Reid <dgreid@chromium.org>