UPSTREAM: ipv6: Remove unused arguments for __ipv6_dev_get_saddr().
BUG=chrome-os-partner:43435
TEST=Fixes 6/8 of run_net_test.sh srcaddr_selection_test.py tests, except:
  - OptimisticAddressTest.testRfc6724Behaviour:
    error: [Errno 99] Cannot assign requested address
  - NoNsFromOptimisticTest.testSendToOnlinkDestination
    UnexpectedPacketError: link-local NS: diff with last packet: [...]

Signed-off-by: YOSHIFUJI Hideaki <hideaki.yoshifuji@miraclelinux.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

(cherry picked from commit c15df306fc79c672573f1cc2ebdfcb32d7e68780 from net-next)
Signed-off-by: Filipe Brandenburger <filbranden@chromium.org>

Change-Id: I250b55fe0bded894bdc974af86fd490fd86da19c
Reviewed-on: https://chromium-review.googlesource.com/296698
Commit-Ready: Filipe Brandenburger <filbranden@chromium.org>
Tested-by: Filipe Brandenburger <filbranden@chromium.org>
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Reviewed-by: Lorenzo Colitti <lorenzo@google.com>