ANDROID: nf: IDLETIMER: Fix broken uid field in the msg
Create uid from kuid to fix the broken uid field
in the message notifications introduced in
Otherwise we run into following build error:
---------------
  CC      net/netfilter/xt_IDLETIMER.o
net/netfilter/xt_IDLETIMER.c: In function ‘reset_timer’:
net/netfilter/xt_IDLETIMER.c:360:16: error: incompatible types when assigning to type ‘uid_t’ from type ‘kuid_t’
make[2]: *** [net/netfilter/xt_IDLETIMER.o] Error 1
---------------

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
(cherry picked from commit 706060ba3e1dee9ec3c4a4a1480d663b6cd71cad)

(cherry picked from commit 7ccfbeceea23c64d110cf8f77803f12d0bcee787)
Signed-off-by: Stephen Barber <smbarber@chromium.org>

BUG=none
TEST=kernel compiles and boots

Change-Id: Iaa4e862806936d7533182bbccd639e741d81dc57
Reviewed-on: https://chromium-review.googlesource.com/281740
Reviewed-by: Dylan Reid <dgreid@chromium.org>
Tested-by: Stephen Barber <smbarber@chromium.org>
Commit-Queue: Stephen Barber <smbarber@chromium.org>