UPSTREAM: ASoC: Intel: Skylake: Add I2C depends for SKL machine
The i2c is dependency for the i2c codec drivers, so machine should depend on
i2c. WIthout this we get build failures if I2C is not selected

   sound/soc/codecs/rl6347a.c: In function 'rl6347a_hw_write':
>> sound/soc/codecs/rl6347a.c:66:8: error: implicit declaration of function
>> 'i2c_master_send' [-Werror=implicit-function-declaration]
     ret = i2c_master_send(client, data, 4);
           ^
   sound/soc/codecs/rl6347a.c: In function 'rl6347a_hw_read':
>> sound/soc/codecs/rl6347a.c:114:8: error: implicit declaration of function
>> 'i2c_transfer' [-Werror=implicit-function-declaration]
     ret = i2c_transfer(client->adapter, xfer, 2);

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Vinod Koul <vinod.koul@intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
Link: git://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git
br: for-next
(cherry picked from commit 0928e8a54bf8889176175b2c3e5f2fc8ec1bb7ff)
Signed-off-by: Vedang Patel <vedang.patel@intel.com>

BUG=None
TEST=with the whole series applied, audio works on SKL.
TEST=there are no regressions observed on BSW.

Change-Id: Idacba68d4aa0e349f9cc4094d46ed06904d0db81
Reviewed-on: https://chromium-review.googlesource.com/316119
Commit-Ready: Radhakrishna Sripada <radhakrishna.sripada@intel.com>
Tested-by: Sathyanarayana Nujella <sathyanarayana.nujella@intel.com>
Reviewed-by: Derek Basehore <dbasehore@chromium.org>