CHROMIUM: net: ipv6: vti: ip6_update_pmtu() has an additional parameter
Commit ba3d8d3f9 ("net: core: Support UID-based routing") added a new
parameter to ip6_update_pmtu(). Commit fa9ad96d4905 ("vti6: Update the ipv6
side to use its own receive hook") neglects to set it, resulting in a build
failure if the feature is enabled.

pv6/ip6_vti.c: In function 'vti6_err':
net/ipv6/ip6_vti.c:559:3: error: too few arguments to function 'ip6_update_pmtu'

Fixes: fa9ad96d4905 ("vti6: Update the ipv6 side to use its own receive hook")
Fixes: ba3d8d3f9f65 ("net: core: Support UID-based routing")
BUG=chromium:583462
TEST=None (build)

Change-Id: I4b0fe120186c7bd225eae1ca88be91d5a1aed269
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325463
Reviewed-by: Dylan Reid <dgreid@chromium.org>