CHROMIUM: usb: tegra: USB_XHCI_TEGRA does not build with COMPILE_TEST
Attempts to build USB_XHCI_TEGRA with COMPILE_TEST on non-ARM
architectures results in a large number of error messages.

drivers/built-in.o: In function `tegra_xhci_powergate':
xhci-tegra.c:(.text+0x1dd80c8):
	undefined reference to `tegra_xusb_usb3_phy_wake_enable'
xhci-tegra.c:(.text+0x1dd811c):
	undefined reference to `tegra_xusb_utmi_phy_wake_enable'
xhci-tegra.c:(.text+0x1dd8155):
	undefined reference to `tegra_xusb_hsic_phy_wake_enable'
xhci-tegra.c:(.text+0x1dd8416):
	undefined reference to `tegra_xusb_utmi_phy_get_pad_config'
xhci-tegra.c:(.text+0x1dd8515):
	undefined reference to `tegra_xusb_utmi_phy_is_dual_role'
drivers/built-in.o: In function `tegra_xhci_unpowergate':
xhci-tegra.c:(.text+0x1dd8afb):
	undefined reference to `tegra_xusb_utmi_clear_vbus_override'
xhci-tegra.c:(.text+0x1dd8b1d):
	undefined reference to `tegra_xusb_usb3_phy_wake_disable'
xhci-tegra.c:(.text+0x1dd8b53):
	undefined reference to `tegra_xusb_utmi_phy_wake_disable'
xhci-tegra.c:(.text+0x1dd8b89):
	undefined reference to `tegra_xusb_hsic_phy_wake_disable'
xhci-tegra.c:(.text+0x1dd8c35):
	undefined reference to `tegra_xusb_utmi_phy_is_dual_role'
drivers/built-in.o: In function `tegra_xhci_resume':
xhci-tegra.c:(.text+0x1dd8d93):
	undefined reference to `tegra_xusb_utmi_clear_vbus_override'
drivers/built-in.o: In function `tegra_xhci_remove':
xhci-tegra.c:(.text+0x1dd9329):
	undefined reference to `tegra_xusb_utmi_phy_is_dual_role'

Fixes: ab5db43688cb7 ("FROMLIST: usb: xhci: Add NVIDIA Tegra xHCI host-controller driver")
BUG=chromium:583462
TEST=None (build)

Change-Id: I683f4ed1dd01bfec2db38ed621db2f6efc87baa8
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325530
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>