CHROMIUM: power: Introduce HAVE_SUSPEND_VOLATILE
Various architectures experience build failures such as

drivers/built-in.o: In function `phys_addrs_overlap':
include/linux/addr_overlap.h:35:
		undefined reference to `__stop_suspend_volatile_bss'
include/linux/addr_overlap.h:35:
	undefined reference to `__stop_suspend_volatile_bss'
include/linux/addr_overlap.h:38:
	undefined reference to `__start_suspend_volatile_bss'
include/linux/addr_overlap.h:38:
	undefined reference to `__start_suspend_volatile_bss'

Instead of trying to define the missing symbols for each affected architecture,
introduce HAVE_SUSPEND_VOLATILE, to be set by each architecture tested
and known to support the respective functionality.

Fixes: 9a1f73196c967 ("CHROMIUM: bitfix: add new suspend_volatile data annotation")
Fixes: 3b078fa546521 ("PM / Sleep: Add the concept of suspend_volatile")
BUG=chromium:583462
TEST=None (build)

Change-Id: I5e3149cb6cfd57c04a18a2466699ce0f90fb073f
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325473
Reviewed-by: Douglas Anderson <dianders@chromium.org>