CHROMIUM: regulator: fixed: Fix build as module
There can only be one module_init() and one module_exit().
subsys_initcall() is converted to module_init() if built
as module, resulting in build errors.

drivers/regulator/fixed.c:249:1: error: redefinition of '__inittest'
drivers/regulator/fixed.c:219:1: note:
	previous definition of '__inittest' was here
drivers/regulator/fixed.c:249:1: error: redefinition of 'init_module'
drivers/regulator/fixed.c:219:1: note:
	previous definition of 'init_module' was here
drivers/regulator/fixed.c:255:1: error: redefinition of '__exittest'
drivers/regulator/fixed.c:225:1: note:
	previous definition of '__exittest' was here
drivers/regulator/fixed.c:255:1: error: redefinition of 'cleanup_module'
drivers/regulator/fixed.c:225:1: note:
	previous definition of 'cleanup_module' was here

On a higher level, the late(r) registration should not be necessary,
since the driver is supposed to defer registration if the problem
it tries to solve occurs.

Fixes: 9c366218fcfa ("CHROMIUM: regulator: fixed: add provision to register driver little late")
BUG=chromium:583462
TEST=None (build)

Change-Id: I5876cd149a270e58f8d6cd27cbc8e0c498ffbf87
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325520
Reviewed-by: Douglas Anderson <dianders@chromium.org>