CHROMIUM: power: Add dummy functions for wakeup reason API
If CONFIG_SUSPEND is not configured, the build fails with

main.c:(.text+0x340c2): undefined reference to `log_suspend_abort_reason'

and similar errors.

Fixes: 582c3df01a30 ("Power: add an API to log wakeup reasons")
BUG=chromium:583462
TEST=None (build)

Change-Id: Ie40861ac84ec70851c569d158ef8da137dcdd0b2
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325345