CHROMIUM: security: tlk_driver: Only build on ARM and ARM64
Other architectures bail out with

security/tlk_driver/ote_comms.c:30:26: fatal error:
	asm/smp_plat.h: No such file or directory

Fixes: 54ec74974e68a ("CHROMIUM: security: tlk_driver: ensure VPR SMC occurs on CPU0")
Fixes: 1e91231f8d658 ("CHROMIUM: tlk: New API changes for tlk")
BUG=chromium:583462
TEST=None (build)

Change-Id: I2a5a52df5877b17ec1c70ed46666d0a44f136ae0
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325455
Reviewed-by: Dylan Reid <dgreid@chromium.org>