UPSTREAM: PM / Domains: Remove unusable governor dummies
The governor dummies for the !CONFIG_PM_GENERIC_DOMAINS case are
unusable, as a governors is always referred to by taking its address,
which you can't do with a literal NULL pointer.

I.e.

	pm_genpd_init(genpd, &simple_qos_governor, false);

fails to compile with:

	error: lvalue required as unary '&' operand

Hence just remove the governor dummies.

Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
Acked-by: Ulf Hansson <ulf.hansson@linaro.org>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit ad440bf40e2846966da44e885bb7d8a1f8384fa6)
Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>
[djkurtz: minor context conflict b/c chromeos-3.18 does not have
 commit d30d819dc831 ("PM: Drop CONFIG_PM_RUNTIME from the driver core")
]

BUG=chromium:571567
TEST=build & boot to UI on oak-rev4
TEST=build & CQ test smaug, strago

Change-Id: I80a53bd78e4fc19e3144cfdcca3286bb548897b1
Reviewed-on: https://chromium-review.googlesource.com/319770
Commit-Ready: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>