CHROMIUM: Select CONFIG_OF in cherryview pinctrl kconfig
An update to include/linux/pinctrl.h breaks the build when cherryview
pinctrl driver is enabled. This patch fixes the error

drivers/pinctrl/pinconf-generic.c:134:20: error: 'struct pinctrl_desc'
has no member named 'num_dt_params'
  if (!pctldev->desc->num_dt_params || !pctldev->desc->conf_items)

BUG=chrome-os-partner:39522
TEST=Enable pinctrl driver and build kernel

Change-Id: I26df45293a791936a39afdbad59f175c5f4f4231
Signed-off-by: Dhinakaran Pandiyan <dhinakaran.pandiyan@intel.com>
Reviewed-on: https://chromium-review.googlesource.com/268907
Reviewed-by: Eric Caruso <ejcaruso@chromium.org>