CHROMIUM: pinctrl: tegra-xusb: enforce all dependencies with 'select'
Trying to build various defconfigs (e.g., multi_v7_defconfig) results in
problems:

  #
  # configuration written to .config
  #
  warning: (PINCTRL_TEGRA124_XUSB && PINCTRL_TEGRA210_XUSB) selects
  PINCTRL_TEGRA_XUSB which has unmet direct dependencies (PINCTRL &&
  MAILBOX)

  drivers/built-in.o: In function `tegra_xusb_padctl_remove':
  :(.text+0xb844): undefined reference to `mbox_free_channel'
  drivers/built-in.o: In function `tegra_xusb_padctl_probe':
  :(.text+0xc5b0): undefined reference to `mbox_request_channel'
  drivers/built-in.o: In function `tegra124_handle_message':
  :(.text+0xd0a8): undefined reference to `mbox_send_message'

Convert all of these to 'select', since a mixture of the two creates
problems when 'select'ing a symbol that might have even more
dependencies.

Adding MAILBOX to PINCTRL_TEGRA124_XUSB and PINCTRL_TEGRA210_XUSB
because they also use mbox_*() APIs.

BUG=chromium:529437
TEST=build multi_v7_defconfig

Change-Id: I7e0055bc384dfe4eb9c2ffb01e5777726a1453ba
Fixes: 59a5b03b30be ("CHROMIUM: pinctrl: tegra-xusb: Split out Tegra124-specific bits")
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/298162
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>