CHROMIUM: mfd: cros_ec: Remove other-writable access from lightbar sysfs
Having other-writable files is no longer allowed since this upstream commit:
  37549e94c77a sysfs: disallow world-writable files.

Without these changes, build fails with:

  drivers/mfd/cros_ec_lightbar.c:406:429: error: negative width in bit-field '<anonymous>'
  static DEVICE_ATTR(brightness, S_IWUGO, NULL, store_brightness);

Change-Id: I6dc62afbf32b27a4bdd4604907728bde9018c7f2
[filbranden: 3.18 rebase. Introduced commit to fix build error.]
Signed-off-by: Filipe Brandenburger <filbranden@chromium.org>