CHROMIUM: hid: quickstep: Remove world-writable access from "clear" device
Having world-writable sysfs devices is no longer allowed since:
  37549e94c77a sysfs: disallow world-writable files.

Without this change, build fails with:
  drivers/hid/hid-quickstep.c:78:329: error: negative width in bit-field '<anonymous>'
  static DEVICE_ATTR(clear, 0222, NULL, clear_log);

Confirmed with Charlie Mooney <charliemooney@chromium.org> that it's OK
to have this device be writable only by owner and group.

Change-Id: If82a2f4236e00df89c3fd0be3c6c035228ac1edf
[filbranden: 3.18 rebase. Introduced commit to fix build error.]
Signed-off-by: Filipe Brandenburger <filbranden@chromium.org>