CHROMIUM: usb: gadget: f_accessory: Declare unused function as maybe_unused
Without this, we get this warning:
.../drivers/usb/gadget/function/f_accessory.c:1172:12:
  error: 'acc_bind_config' defined but not used [-Werror=unused-function]
 static int acc_bind_config(struct usb_configuration *c)
            ^

Arguably, the function could be removed, but it looks like the
intent of drivers/usb/gadget/android.c is to include this file, so
leave it be.

BUG=chromium:534254
TEST=emerge-smaug chromeos-kernel-3_18

Change-Id: I5f66083372ac4eae587127bca41ea32c6864b4e5
Signed-off-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/305153
Reviewed-by: Olof Johansson <olofj@chromium.org>