CHROMIUM: irqchip: gic: don't confuse assembler with an enum
When compile-testing some KVM code, I ran across this error:

    include/linux/irqchip/arm-gic.h: Assembler messages:
    include/linux/irqchip/arm-gic.h:93: Error: unknown mnemonic `enum' -- `enum domain_gic_pm_event{'
    include/linux/irqchip/arm-gic.h:94: Error: unknown mnemonic `mod_domain_power_on' -- `mod_domain_power_on,'
    include/linux/irqchip/arm-gic.h:95: Error: unknown mnemonic `mod_domain_power_off' -- `mod_domain_power_off'
    include/linux/irqchip/arm-gic.h:96: Error: junk at end of line, first unrecognized character is `}'

BUG=chromium:529437
TEST=compile arm64 defconfig

Change-Id: I2292f977324005fae83a9c414bb26f0c9fcd4813
Fixes: 0bace00d8231 ("CHROMIUM: irqchip: Add ability to notify non per-cpu GICs")
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/298163
Reviewed-by: Ajay Nandakumar <anandakumarm@nvidia.com>
Reviewed-by: Anatol Pomazau <anatol@google.com>