CHROMIUM: ASoC: wm9712: Fix build errors
sound/soc/codecs/wm9712.c:175:17: error:
	'struct snd_soc_dapm_widget' has no member named 'codec'

Missed back-port (maybe on purpose) of commit cf1f2ebe8d617 ("ASoC:
wm9712/wm9713: Replace virtual registers with custom put/get callbacks").

sound/soc/codecs/wm9712.c:542:2: error:
	unknown field 'ac97_control' specified in initializer

Missed by commit 19f56582d0dd (UPSTREAM: ASoC: Rename snd_soc_dai_driver struct
ac97_control field to bus_control"). Maybe there is some other patch missing.

Fixes: 33dac9ed64a6 ("UPSTREAM: ASoC: Remove codec field from snd_soc_dapm_widget")
Fixes: 19f56582d0dd ("UPSTREAM: ASoC: Rename snd_soc_dai_driver struct ac97_control field to bus_control")
BUG=chromium:583462
TEST=None (build)

Change-Id: If5bc0832194622d558626f32779882105f20f8e0
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325346
Reviewed-by: Anatol Pomazau <anatol@google.com>