Revert "CHROMIUM: arch: arm: dma: add dma_alloc_at_coherent"
This reverts commit 9d3cc223a79090c66d6269bc43fc4e4506f4b479.

Trying to build this feature (file) results in

arch/arm/mm/dma-mapping.c: In function '__alloc_iova_at':
arch/arm/mm/dma-mapping.c:1073:17: error:
	'struct dma_iommu_mapping' has no member named 'order'

arch/arm/mm/dma-mapping.c:1083:44: error:
	'struct dma_iommu_mapping' has no member named 'bitmap'

and will need to be re-implemented.

BUG=chromium:583462
TEST=None (build)

Change-Id: I7bda6fd53c3c39486bf9b46572e6a862a0eb65d6
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325304
Reviewed-by: Douglas Anderson <dianders@chromium.org>