CHROMIUM: net: rfkill: rfkill_resume_polling() is needed outside CONFIG_RFKILL_PM
Fix the following build error.

ERROR: "rfkill_resume_polling" [net/wireless/cfg80211.ko] undefined!

Fixes: 1fb6edeb817a ("rfkill: Introduce CONFIG_RFKILL_PM and use instead of CONFIG_PM to power down")
BUG=chromium:583462
TEST=None (build)

Change-Id: I031ad02ae0b134ceef9e6e2e387abf0e58831884
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325500
Reviewed-by: Dylan Reid <dgreid@chromium.org>