UPSTREAM: ASoC: Intel: fix build with runtime PM disabled.
Fix the following errors:

All error/warnings:

>> sound/soc/intel/sst-haswell-pcm.c:1168:13: error: 'hsw_pcm_prepare' undeclared here (not in a function)
     .prepare = hsw_pcm_prepare,
                ^
>> sound/soc/intel/sst-haswell-pcm.c:1169:14: error: 'hsw_pcm_complete' undeclared here (not in a function)
     .complete = hsw_pcm_complete,
                 ^
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>

(cherry picked from commit 35e03a884c41b8fecf77e20de89759deb7c9078a)
BUG=chrome-os-partner:40036
TEST=Audio playback works on test device

Change-Id: I29383b1d6f0322ec07547589ed7bfed0afedb0e3
Reviewed-on: https://chromium-review.googlesource.com/270865
Reviewed-by: Dylan Reid <dgreid@chromium.org>
Commit-Queue: Bernie Thompson <bhthompson@chromium.org>
Tested-by: Bernie Thompson <bhthompson@chromium.org>