CHROMIUM: alt-syscall: Include asm/syscall.h conditionally
To avoid build failures, only include asm/syscall.h if needed.

init/init_task.c:12:25: fatal error:
	asm/syscall.h: No such file or directory
include/linux/alt-syscall.h:7:25: error:
	asm/syscall.h: No such file or directory

Fixes: 7cbfd8622698 ("CHROMIUM: x86: implement thread_info-based syscall table")
BUG=chromium:583462
TEST=None (build)

Change-Id: Ifb696ab6c837a3dc71d3052aecd5391647196c9b
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325395
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>