CHROMIUM: net: tcp: Export tcp_nuke_addr
Otherwise compilation may fail if IPv6 is built as module.

ERROR: "tcp_nuke_addr" [net/ipv6/ipv6.ko] undefined!

Fixes: c7c3ec4903d3 ("net: socket ioctl to reset connections matching local address")
BUG=chromium:583462
TEST=None (build)

Change-Id: Ib18a74aa251cfd3674aa152442a52552e59123b3
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325462
Reviewed-by: Dylan Reid <dgreid@chromium.org>