Revert "UPSTREAM: mmc: mediatek: Add PM support for MMC driver"
This reverts commit a779776956dd50d0f3ebe263341278cf899f41e6.

Paul Gortmaker <paul.gortmaker@windriver.com> reported on the
mailing list that this commit broke linux-next since it gets
exposed as an implicit module.h user that does not include
module.h

   drivers/mmc/host/mtk-sd.c:1459:1: note: in expansion of macro
'module_platform_driver'
    module_platform_driver(mt_msdc_driver);
    ^
   include/linux/device.h:1296:1: error: type defaults to 'int' in
declaration of 'module_init' [-Werror=implicit-int]
    module_init(__driver##_init); \
    ^

mmc maintainer Ulf Hansson <ulf.hansson@linaro.org> rebased his
mmc/next branch from which this patch was originally taken.

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chrome-os-partner:38746
TEST=build and boot oak-rev2

Change-Id: I0f04970d0375e544d5c99049dceb7463fb50be50
Reviewed-on: https://chromium-review.googlesource.com/280392
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Trybot-Ready: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>