UPSTREAM: ipv6: Do not iterate over all interfaces when finding source address on specific interface.
If outgoing interface is specified and the candidate address is
restricted to the outgoing interface, it is enough to iterate
over that given interface only.

BUG=chrome-os-partner:43435
TEST=Fixes 6/8 of run_net_test.sh srcaddr_selection_test.py tests, except:
  - OptimisticAddressTest.testRfc6724Behaviour:
    error: [Errno 99] Cannot assign requested address
  - NoNsFromOptimisticTest.testSendToOnlinkDestination
    UnexpectedPacketError: link-local NS: diff with last packet: [...]

Signed-off-by: YOSHIFUJI Hideaki <hideaki.yoshifuji@miraclelinux.com>
Acked-by: Erik Kline <ek@google.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

(cherry picked from commit 9131f3de24db4dc12199aede7d931e6703e97f3b from net-next)
Signed-off-by: Filipe Brandenburger <filbranden@chromium.org>

Change-Id: I53112dd8ee892fe073e5b1dff2d30c573078b505
Reviewed-on: https://chromium-review.googlesource.com/296696
Commit-Ready: Filipe Brandenburger <filbranden@chromium.org>
Tested-by: Filipe Brandenburger <filbranden@chromium.org>
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Reviewed-by: Lorenzo Colitti <lorenzo@google.com>