UPSTREAM: arm: omap3: twl: remove usb phy init data
commit dbc98635e0d4 ("phy: remove the old lookup method") removes
struct phy_consumer but twl-common.c still uses the "phy_consumer"
structure resulting in the following compilation warning.

arch/arm/mach-omap2/twl-common.c:94:21: error: array type has
incomplete element type
 struct phy_consumer consumers[] = {

Removed using phy_consumer since twl4030 uses the new lookup
method.

Signed-off-by: Heikki Krogerus <heikki.krogerus@linux.intel.com>
Signed-off-by: Kishon Vijay Abraham I <kishon@ti.com>
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Greg Kroah-Hartman <greg@kroah.com>
(cherry picked from commit 81e1dadfb5b2d47aa513ad60b1c9cf0ea17b6514)

BUG=chromium:529437
TEST=build ARM32 multi_v7_defconfig

Change-Id: I9c1d11c854738e243a95080aa9dabd4c7378acdb
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/298165
Reviewed-by: Olof Johansson <olofj@chromium.org>