CHROMIUM: drm: img-rogue: Add architecture dependencies
The img-rogue driver will only compile for a few architectures,
and otherwise fail to build with

drivers/gpu/drm/img-rogue/pmr_os.c: In function 'OSMMapPMRGeneric':
drivers/gpu/drm/img-rogue/pmr_os.c:258:2: error:
	#error Please add pgprot_modify equivalent for your system

Fixes: 630ae227f2b7 ("CHROMIUM: drm/img-rogue: add kernel driver from img-ddk 1.6@3710675")
BUG=chromium:583462
TEST=None (build)

Change-Id: Id2e7bd5802a414bcf903fa6af605c914806ee770
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325305
Commit-Ready: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>