UPSTREAM: ipv6: Fix finding best source address in ipv6_dev_get_saddr().
Commit 9131f3de2 ("ipv6: Do not iterate over all interfaces when
finding source address on specific interface.") did not properly
update best source address available.  Plus, it introduced
possible NULL pointer dereference.

Bug was reported by Erik Kline <ek@google.com>.
Based on patch proposed by Hajime Tazaki <thehajime@gmail.com>.

BUG=chrome-os-partner:43435
TEST=Fixes 6/8 of run_net_test.sh srcaddr_selection_test.py tests, except:
  - OptimisticAddressTest.testRfc6724Behaviour:
    error: [Errno 99] Cannot assign requested address
  - NoNsFromOptimisticTest.testSendToOnlinkDestination
    UnexpectedPacketError: link-local NS: diff with last packet: [...]

Fixes: 9131f3de24db4dc12199aede7d931e6703e97f3b ("ipv6: Do not
	iterate over all interfaces when finding source address
	on specific interface.")
Signed-off-by: YOSHIFUJI Hideaki <hideaki.yoshifuji@miraclelinux.com>
Acked-by: Hajime Tazaki <thehajime@gmail.com>
Acked-by: Erik Kline <ek@google.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

(cherry picked from commit c0b8da1e7613a11ce7e44560aae507b62da1f846 from net-next)
Signed-off-by: Filipe Brandenburger <filbranden@chromium.org>

Change-Id: I39481eb4eb9c26c6bd150a2cb2b36192fcfe2d13
Reviewed-on: https://chromium-review.googlesource.com/296697
Commit-Ready: Filipe Brandenburger <filbranden@chromium.org>
Tested-by: Filipe Brandenburger <filbranden@chromium.org>
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Reviewed-by: Lorenzo Colitti <lorenzo@google.com>