CHROMIUM: drm: tegra: dc: Use DIV_ROUND_UP_ULL
When using DIV_ROUND_UP, 32 bit builds fail with

drivers/built-in.o: In function `tegra_dc_set_latency_allowance.isra.21':
:(.text+0x134d34): undefined reference to `__aeabi_uldivmod'

Fixes: 331dd4c9b5e7 ("CHROMIUM: drm/tegra: Correct MC latency allowance")
BUG=chromium:583462
TEST=None (build)

Change-Id: I5a9e4d8ecb0f16ba991228a00e3edb75c328f045
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325399
Reviewed-by: Sean Paul <seanpaul@google.com>