UPSTREAM: ALSA: hda/tegra - Fix build error and warning
I seem to have failed to run the build test properly...
   sound/pci/hda/hda_tegra.c: In function 'hda_tegra_dev_free':
   sound/pci/hda/hda_tegra.c:310:20: error: 'bus' undeclared (first use in this function)
         snd_hdac_bus_exit(bus);

Reported-by: kbuild test robot <fengguang.wu@intel.com>
BUG=chromium:583462
TEST=None (build)

Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit 4cfe99c7f9592573e85a9768cfb2a8d7a7962618)
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>

Change-Id: I4ccb5eef000baaff573f92db218330ac47d186f5
Reviewed-on: https://chromium-review.googlesource.com/325458
Commit-Ready: Olof Johansson <olofj@chromium.org>
Tested-by: Olof Johansson <olofj@chromium.org>
Reviewed-by: Dylan Reid <dgreid@chromium.org>