CHROMIUM: ASoC: rt5677: Add missing include file
Commit a997ffe5eab3 ("CHROMIUM: ASoC: rt5677: add of_match to rt5677-spi") added
devicetree functions without including linux/of.h, resulting in the following
build error on some architectures.

sound/soc/codecs/rt5677-spi.c:251:3: error:
	implicit declaration of function 'of_match_ptr'
sound/soc/codecs/rt5677-spi.c:251:34: error:
	'rt5677_spi_of_match' undeclared here

Fixes: a997ffe5eab3 ("CHROMIUM: ASoC: rt5677: add of_match to rt5677-spi")
BUG=chromium:583462
TEST=None (build)

Change-Id: I22cefcdafe1e65c2ca2301d76a81021eb5f7bd42
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325482
Reviewed-by: Ben Zhang <benzh@chromium.org>