CHROMIUM: drm/nouveau: pmu: gm20b: Do not use variable before it is set
drivers/gpu/drm/nouveau/nvkm/subdev/pmu/gm20b.c:
	In function 'gm20b_pmu_ctor':
drivers/gpu/drm/nouveau/nvkm/subdev/pmu/gm20b.c:2539:1: error:
	'ppmu' may be used uninitialized in this function

Fixes: 17aa40b8c56a ("drm/nouveau: pmu: gm20b: Fixes memory leaks.")
BUG=chromium:583462
TEST=None (build)

Change-Id: I5fa375a6aaf36cd0342214d94205861ac8bdc9a2
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325454
Reviewed-by: Sean Paul <seanpaul@google.com>