UPSTREAM: ipv6: sysctl to restrict candidate source addresses
Per RFC 6724, section 4, "Candidate Source Addresses":

    It is RECOMMENDED that the candidate source addresses be the set
    of unicast addresses assigned to the interface that will be used
    to send to the destination (the "outgoing" interface).

Add a sysctl to enable this behaviour.

BUG=chrome-os-partner:43435
TEST=Fixes 6/8 of run_net_test.sh srcaddr_selection_test.py tests, except:
  - OptimisticAddressTest.testRfc6724Behaviour:
    error: [Errno 99] Cannot assign requested address
  - NoNsFromOptimisticTest.testSendToOnlinkDestination
    UnexpectedPacketError: link-local NS: diff with last packet: [...]

Signed-off-by: Erik Kline <ek@google.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

(cherry picked from commit 3985e8a3611a93bb36789f65db862e5700aab65e from net-next)
Signed-off-by: Filipe Brandenburger <filbranden@chromium.org>

Change-Id: If2d829657062e34222154743191fc24cd367e90e
Reviewed-on: https://chromium-review.googlesource.com/296699
Commit-Ready: Filipe Brandenburger <filbranden@chromium.org>
Tested-by: Filipe Brandenburger <filbranden@chromium.org>
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Reviewed-by: Lorenzo Colitti <lorenzo@google.com>