CHROMIUM: chrome: Have CHROMEOS_VBC_EC select MFD_CROS_EC instead of depending on it
If CHROMEOS_VBC_EC depends on MFD_CROS_EC, MFD_CROS_EC can be built as module,
which results in

drivers/built-in.o: In function `vbc_write.isra.2':
chromeos_vbc_ec.c:(.text+0x26f603):
	undefined reference to `cros_ec_cmd_xfer_status'
drivers/built-in.o: In function `vbc_read.isra.3':
chromeos_vbc_ec.c:(.text+0x26f8d6):
	undefined reference to `cros_ec_cmd_xfer_status'

By selecting MFD_CROS_EC instead, MFD_CROS_EC will be built into the kernel.

Alternative would be to make MFD_CROS_EC boolean.

BUG=chromium:583462
TEST=None (build)

Change-Id: I332a920e5b5410afdb27c207c38b44eb2f5455f1
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325503
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>