CHROMIUM: tpm: i2c_infineon: Mark suspend/resume functions as __maybe_unused
Avoid the following build error.

drivers/char/tpm/tpm_i2c_infineon.c:703:12: error:
	'tpm_tis_i2c_suspend' defined but not used
drivers/char/tpm/tpm_i2c_infineon.c:711:12: error:
	'tpm_tis_i2c_resume' defined but not used

Fixes: e852a6edd024 ("CHROMIUM: tpm: do not suspend/resume if power stays on")
BUG=chromium:583462
TEST=None (build)

Change-Id: I5479fcfce64273dac88d930705d52e5ee7c67435
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325448
Reviewed-by: Luigi Semenzato <semenzato@chromium.org>